# Generated by Django 3.1.7 on 2021-03-28 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Abbr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(help_text='british english', max_length=400)),
                ('description_ae', models.CharField(blank=True, help_text='american english', max_length=400)),
                ('wiki', models.CharField(blank=True, help_text='wikipedia summary', max_length=9999, null=True)),
            ],
            options={
                'ordering': ['name', 'description'],
                'unique_together': {('name', 'description')},
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abbr.abbr')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['abbr', 'user'],
                'unique_together': {('abbr', 'user')},
            },
        ),
    ]
