# Generated by Django 3.1.7 on 2021-03-28 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abbr', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
