# Generated by Django 3.1.7 on 2021-04-07 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abbr', '0002_delete_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abbr',
            name='description_ae',
        ),
    ]
